######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 18 10:01:47 2014
######################################################################

TEMPLATE = app
OBJECTS_DIR = build
DESTDIR = bin

include("genericParser.pri")

SOURCES += test/main.cpp
